README.md
circle.yml
package.json
src/bin/integration
src/index.js
src/lib/dependency-manager.js
src/lib/service-manager.js
src/tests/index.js
src/util/index.js

Fixes https://github.com/interledger/five-bells-integration-test/issues/2

[FEATURE] add tests

---

src/lib/service-manager.js

https://github.com/interledger/five-bells-ledger/pull/215

fix: Ledger uses four digits of precision after decimal point

---

src/lib/service-manager.js

Requires https://github.com/interledger/five-bells-connector/pull/138 and https://github.com/interledger/five-bells-sender/pull/56

feat: move pathfinder to connector

---

package.json
src/lib/dependency-manager.js
src/lib/service-manager.js
src/tests/index.js

This migrates Five Bells to the new crypto-conditions format. See https://github.com/interledger/five-bells-condition
Requires interledger/five-bells-ledger#233, interledger/five-bells-connector#146, interledger/five-bells-notary#57, interledger/five-bells-sender#63 and a new module [interledger/five-bells-receiver](https://github.com/interledger/five-bells-receiver).

New crypto-conditions

---

src/tests/index.js

Requires https://github.com/interledger/five-bells-ledger/pull/238
Requires https://github.com/interledger/five-bells-connector/pull/150
Requires https://github.com/interledger/five-bells-sender/pull/65

[FEATURE] slippage; use scale=4 correctly

---

src/tests/index.js

This will pass as soon as https://github.com/interledger/five-bells-sender/pull/73 is merged.

test: add test for same ledger payment

---

src/lib/service-manager.js
src/tests/index.js

Adjust the test values for the new rounding adjustments in https://github.com/interledger/five-bells-connector/pull/161

test: fix rounding issue

---

src/bin/integration
src/lib/service-graph.js
src/lib/service-manager.js
src/tests/advanced.js
src/tests/index.js

This will conflict with https://github.com/interledger/five-bells-integration-test/pull/22, but can actually supercede it (it fixes the same bug).

test: add tests for scale, spread, slippage, etc

---

src/tests/advanced.js
src/tests/index.js

Update tests for https://github.com/interledger/five-bells-connector/pull/200.

fix: tests for less pessimistic quoting

---

package.json
src/lib/dependency-manager.js
src/lib/service-manager.js

`lib/service-manager` was broken when plugin options were updated in `ilp-core`.

Fix: update plugin options in ilp-core usage

---

src/lib/service-graph.js
src/lib/service-manager.js
src/tests/advanced.js

Depends on https://github.com/interledger/five-bells-connector/pull/206

fix: tests for connector dj-relay-quote

---

package.json
src/lib/dependency-manager.js
src/lib/service-graph.js
src/lib/service-manager.js
src/tests/advanced.js
src/tests/index.js

Fixes #29 
Requires https://github.com/interledger/js-ilp/pull/21

fix: use js-ilp receiver/sender

---

src/lib/dependency-manager.js
src/lib/service-manager.js
src/tests/advanced.js

Depends on:
* https://github.com/interledger/js-ilp-plugin-bells/pull/34, https://github.com/interledger/js-ilp-plugin-bells/pull/36
* https://github.com/interledger/js-ilp/pull/37
* https://github.com/interledger/five-bells-ledger/pull/320
* https://github.com/interledger/js-ilp-connector/pull/211

feat: add tests for rejectIncomingTransfer

---

src/lib/service-manager.js

Related to https://github.com/interledger/js-ilp-connector/issues/212

fix: CONNECTOR_AUTOLOAD_PEERS=true

---

src/tests/advanced.js

See https://github.com/interledger/js-ilp/pull/45/commits/011e2589ee6f8cf8e42251745113dcacb75f6b7c

fix: receivers shouldn't reject tx w/ bad conditions

---

src/tests/advanced.js
src/tests/index.js

Depends on https://github.com/interledger/js-ilp-connector/pull/218

feat: test trivial rate

---

src/tests/advanced.js
src/tests/index.js

Depends on https://github.com/interledger/five-bells-ledger/pull/325 and https://github.com/interledger/js-ilp-plugin-bells/pull/46

fix: update error names/messages

---

package.json
src/tests/advanced.js
src/tests/index.js

Requires https://github.com/interledgerjs/ilp-plugin-bells/pull/58, https://github.com/interledgerjs/five-bells-ledger/pull/336, https://github.com/interledgerjs/ilp-core/pull/59, https://github.com/interledgerjs/ilp-connector/pull/237, https://github.com/interledgerjs/five-bells-service-manager/pull/3

fix: send routes via /messages

---

circle.yml
package.json
src/tests/advanced.js
src/tests/index.js

Removes unnecessary delays in the integration tests.
Depends on interledgerjs/five-bells-service-manager#4

Improve performance

---

package.json
src/lib/service-graph.js
src/tests/advanced.js
src/tests/index.js

Related to interledgerjs/five-bells-ledger#358 and interledgerjs/five-bells-service-manager#7.

chore: bump service manager version

---

src/bin/integration
src/tests/connector_first.js

Related to https://github.com/interledgerjs/ilp-connector/issues/248

test: add test for when connector starts first

---

package.json
src/lib/kit-manager.js
src/tests/ilp-kit.js

Depends on interledgerjs/five-bells-service-manager#20

feat: Add tests for ILP kit account registration using invites

---

.dockerignore
Dockerfile
README.md
circle.yml
dockercfg-template
src/bin/integration
src/tests/ilp-kit.js

Still not working correctly, but it's starting to show some meaningful output when you run it.

Add Dockerfile

---

Dockerfile
README.md
circle.yml
src/lib/kit-manager.js
src/tests/ilp-kit.js

This PR should be coordinated with https://github.com/interledgerjs/ilp-kit/pull/297

Release 2.0

---

src/lib/service-graph.js
src/tests/advanced.js
src/tests/connector_first.js
src/tests/index.js

Companion to https://github.com/interledgerjs/five-bells-ledger/pull/426

fix: remove hold account tests

---

src/bin/integration
src/tests/ilp-kit.js

- test: Removes check for HTTP status codes
- feat: Prints a more expressive error message if called with wrong args

da-fix-ilpkit-tests

---

Dockerfile
assets/ci/sites-available/wallet1.example.conf
assets/ci/sites-available/wallet2.example.conf
assets/ci/sites-available/wallet3.example.conf

Depends on ilp-kit#v4 and https://github.com/interledgerjs/five-bells-service-manager/pull/34

fix: update apache configs for ilp-kit v4

---

src/tests/advanced.js
src/tests/static_routes.js

Companion to https://github.com/interledgerjs/ilp-connector/pull/392

fix: adapt expected balances to greedy forwarding

---

circle.yml
src/bin/integration

test: supsend ilp kit tests
